name: Build and Deploy Docs

on:
  push:
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs,dev]

      - name: Run tests and generate coverage report
        run: |
          pytest

      - name: Build MkDocs site
        run: mkdocs build
      
      - name: Copy coverage report into site
        run: |
          cp -r htmlcov ./site/htmlcov

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site